name: Quarto Publish

on:
  push:
    branches: ["main"]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true   # Much faster package installs

      # ---------------------------------------------
      # R PACKAGE CACHE  -----------------------------
      # ---------------------------------------------
      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/R
          key: ${{ runner.os }}-r-${{ hashFiles('.github/workflows/main.yml') }}

      - name: Install R packages
        run: |
          Rscript -e "install.packages(c(
              'tidyverse','e1071','caret','ggplot2',
              'AER','dynlm'
           ), repos='https://cloud.r-project.org')"

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Python cache
      - name: Cache Python packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python packages
        run: |
          pip install numpy pandas scikit-learn shap

      # ---------------------------------------------
      # RENDER QUARTO PROJECT ------------------------
      # ---------------------------------------------
      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2

      # ---------------------------------------------
      # DEPLOY ---------------------------------------
      # ---------------------------------------------
      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
